// Code generated by MockGen. DO NOT EDIT.
// Source: domain/inbox_repo.go

// Package domain is a generated GoMock package.
package domain

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockInboxRepo is a mock of InboxRepo interface.
type MockInboxRepo struct {
	ctrl     *gomock.Controller
	recorder *MockInboxRepoMockRecorder
}

// MockInboxRepoMockRecorder is the mock recorder for MockInboxRepo.
type MockInboxRepoMockRecorder struct {
	mock *MockInboxRepo
}

// NewMockInboxRepo creates a new mock instance.
func NewMockInboxRepo(ctrl *gomock.Controller) *MockInboxRepo {
	mock := &MockInboxRepo{ctrl: ctrl}
	mock.recorder = &MockInboxRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInboxRepo) EXPECT() *MockInboxRepoMockRecorder {
	return m.recorder
}

// GetAllInbox mocks base method.
func (m *MockInboxRepo) GetAllInbox() ([]*InboxItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllInbox")
	ret0, _ := ret[0].([]*InboxItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllInbox indicates an expected call of GetAllInbox.
func (mr *MockInboxRepoMockRecorder) GetAllInbox() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllInbox", reflect.TypeOf((*MockInboxRepo)(nil).GetAllInbox))
}

// Store mocks base method.
func (m *MockInboxRepo) Store(item *InboxItem) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Store", item)
	ret0, _ := ret[0].(error)
	return ret0
}

// Store indicates an expected call of Store.
func (mr *MockInboxRepoMockRecorder) Store(item interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Store", reflect.TypeOf((*MockInboxRepo)(nil).Store), item)
}
