// Code generated by MockGen. DO NOT EDIT.
// Source: domain/session_repo.go

// Package domain is a generated GoMock package.
package domain

import (
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
)

// MockSessionRepo is a mock of SessionRepo interface.
type MockSessionRepo struct {
	ctrl     *gomock.Controller
	recorder *MockSessionRepoMockRecorder
}

// MockSessionRepoMockRecorder is the mock recorder for MockSessionRepo.
type MockSessionRepoMockRecorder struct {
	mock *MockSessionRepo
}

// NewMockSessionRepo creates a new mock instance.
func NewMockSessionRepo(ctrl *gomock.Controller) *MockSessionRepo {
	mock := &MockSessionRepo{ctrl: ctrl}
	mock.recorder = &MockSessionRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionRepo) EXPECT() *MockSessionRepoMockRecorder {
	return m.recorder
}

// Pop mocks base method.
func (m *MockSessionRepo) Pop() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Pop")
}

// Pop indicates an expected call of Pop.
func (mr *MockSessionRepoMockRecorder) Pop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Pop", reflect.TypeOf((*MockSessionRepo)(nil).Pop))
}

// QueryData mocks base method.
func (m *MockSessionRepo) QueryData(duration time.Duration) *Days {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryData", duration)
	ret0, _ := ret[0].(*Days)
	return ret0
}

// QueryData indicates an expected call of QueryData.
func (mr *MockSessionRepoMockRecorder) QueryData(duration interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryData", reflect.TypeOf((*MockSessionRepo)(nil).QueryData), duration)
}

// Save mocks base method.
func (m *MockSessionRepo) Save(save *Session) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Save", save)
}

// Save indicates an expected call of Save.
func (mr *MockSessionRepoMockRecorder) Save(save interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockSessionRepo)(nil).Save), save)
}
